### ISSUE TITLE
Request: Ability to have custom server item be held like a weapon

### ISSUE THREAD

**Issue by Entoarox** [ForgeEssentials/CustomServerItems#2]
I am using it for a custom weapon and in third person it is being held all wrong:
![2015-10-03_20 07 07](https://cloud.githubusercontent.com/assets/4977187/10264383/5b89318e-6a0a-11e5-8076-2cd67fe94dbb.png)

**Comment by olee** [comment]
Oh yeah I wanted to add this feature, but I forgot it. Will be added asap. 

PS: Sadly ASAP currently means in about two weeks.
